version: "3.8"

services:
  data-ingestion:
    build:
      context: . # Use the root directory as build context
      dockerfile: data_ingestion/Dockerfile
    volumes:
      - ./data:/data
    env_file:
      - .env
    networks:
      - plagiarism-network
    dns:
      - 8.8.8.8 # Use Google DNS
      - 8.8.4.4
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      vector-db:
        condition: service_healthy

  vector-db:
    build:
      context: . # Use the root directory as build context
      dockerfile: vector_db/Dockerfile
    volumes:
      - ./data:/data
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "from pinecone import Pinecone; import os; pc = Pinecone(api_key=os.getenv('PINECONE_API_KEY')); pc.list_indexes()",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - plagiarism-network
    dns:
      - 8.8.8.8 # Use Google DNS
      - 8.8.4.4

  models:
    build:
      context: .
      dockerfile: models/Dockerfile
    env_file:
      - .env
    networks:
      - plagiarism-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  api:
    build:
      context: . # Use the root directory as build context
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      vector-db:
        condition: service_healthy
      data-ingestion:
        condition: service_completed_successfully
    networks:
      - plagiarism-network
    dns:
      - 8.8.8.8 # Use Google DNS
      - 8.8.4.4

volumes:
  repo-data:

networks:
  plagiarism-network:
    driver: bridge
